services:
  homeassistant:
    image: "homeassistant/home-assistant:${HA_VERSION}"
    container_name: homeassistant
    volumes:
      - "../test_config:/config"
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8123:8123"
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    privileged: true